#!/usr/bin/env python3
"""
SOC Incident Report Generator
Generates Markdown incident reports from detection findings.
"""

from datetime import datetime


SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH": "🟠",
    "MEDIUM": "🟡",
    "LOW": "🟢",
}


class ReportGenerator:
    """Generate SOC-style incident report from findings."""

    def __init__(self, findings: list, log_file: str, log_type: str):
        self.findings = findings
        self.log_file = log_file
        self.log_type = log_type
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    def generate(self) -> str:
        """Generate full Markdown incident report."""
        critical = [f for f in self.findings if f["severity"] == "CRITICAL"]
        high     = [f for f in self.findings if f["severity"] == "HIGH"]
        medium   = [f for f in self.findings if f["severity"] == "MEDIUM"]
        low      = [f for f in self.findings if f["severity"] == "LOW"]

        overall_severity = "LOW"
        if critical: overall_severity = "CRITICAL"
        elif high:   overall_severity = "HIGH"
        elif medium: overall_severity = "MEDIUM"

        report = f"""# 🔐 SOC Incident Report

**Analyst:** [Your Name]  
**Date:** {self.timestamp}  
**Log Source:** `{self.log_file}` ({self.log_type.upper()})  
**Overall Severity:** {SEVERITY_EMOJI.get(overall_severity, '')} {overall_severity}  

---

## Executive Summary

Log analysis identified **{len(self.findings)} alert(s)** across the analyzed log data:

| Severity | Count |
|----------|-------|
| 🔴 Critical | {len(critical)} |
| 🟠 High | {len(high)} |
| 🟡 Medium | {len(medium)} |
| 🟢 Low | {len(low)} |

---

## Findings

"""
        for i, finding in enumerate(self.findings, 1):
            emoji = SEVERITY_EMOJI.get(finding["severity"], "")
            report += f"""### [{i}] {emoji} {finding['title']}

| Field | Detail |
|-------|--------|
| **Severity** | {finding['severity']} |
| **Type** | {finding['type']} |
| **MITRE ATT&CK** | {finding.get('mitre', 'N/A')} |
| **IOCs** | `{'`, `'.join(finding.get('iocs', []))}` |

**Detail:**  
{finding['detail']}

**Sample Log Evidence:**
```
{chr(10).join(finding.get('raw_events', [])[:3])}
```

**Recommended Actions:**
- Investigate source IP(s) in threat intelligence feeds
- Validate whether activity was authorized
- Escalate to Tier 2 if confirmed malicious
- Update SIEM alerting rules based on findings
- Document in ticketing system

---

"""

        report += f"""## Analyst Notes

- [ ] Findings reviewed and validated
- [ ] Escalated to Tier 2 (if required)
- [ ] Ticket created in ITSM system
- [ ] Alert rules updated

---

*Report generated by Log Analyzer Tool | {self.timestamp}*
"""
        return report

    def save(self, filepath: str):
        """Save report to file."""
        report = self.generate()
        with open(filepath, "w") as f:
            f.write(report)
